Tests for BlockChain::insert()ing + state-syncing. Some capitalisation fixes.
Initial compiling version of PoA client.

Fluidity introduced.

Fix tests.

Terminology mining -> sealing.

Renaming away from coinbase.
Fluidity client.

Ethereum client shouldn't be handling exit!

Windows compile fix.

Boundary belongs to Ethash

Difficulty calculation moves to Ethash

Mass draft of how things could look soon

Move tests over to new API.

Route some config info to populateFromHeader calls.

Remove Params.*
Refactor verification code.

Remove verifyParent and other unused verification code/params.

Don't need params in Block.

Moving towards virtuals in API.

Move to a virtual verify.

Moving to virtual API; killing much from BlockHeader.

Remove template code, introduce EthashClient.

Repotting, plugin-style seal engines, ChainParams dictates seal engine.

Fixes to make first test work.

Use a fake version of Frontier for testing to avoid importing genesis
accounts.

Remove Ethash/mining-specific APIs from Interface/Client.

Various fixes and API updates to make tests work.

Tracking stuff to fix more tests.

Fixes for block loading.

Safety checks in test stuff.

Fix uncle data issue.

Fix contract account creation issue.

Final fix for blockchain tests.

Reduce verbosity.

Remove silly API.;

EthashCL fixups.

Optimisation and fixes.

Avoid Ethash/open-network specific stuff in libethereum.

Update test & ethashcl code.

Language cleanup.

Remove canaries from core into Ethash's seal engine.

Don't use 0 difficulty as indicator of invalidiity in details.

add removed unique_ptr.get() back

The get() is needed here because llvm::MemoryBuffer::getFile() does not
actually return a simple unique_ptr but instead returns an `ErrorOr`
construct and as such the compiler needs to first get the pointer and
then get the function of the file. Else it does not compile.

Here is the error I was getting
```
[ 13%] Building CXX object evmjit/libevmjit/CMakeFiles/evmjit.dir/Endianness.cpp.o
/home/lefteris/ew2/libethereum/evmjit/libevmjit/Cache.cpp:121:58: error: no member named 'getBuffer' in 'std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >'
                g_lastObject = llvm::MemoryBuffer::getMemBufferCopy(r->getBuffer());
```

Here is the function signature
```
  static ErrorOr<std::unique_ptr<MemoryBuffer>>
  getFile(const Twine &Filename, int64_t FileSize = -1,
          bool RequiresNullTerminator = true, bool IsVolatileSize =
		  false);
```

Fix clang warnings

- ChainOpeationParams is declared as a struct so forward declaration
should also be so.

- Adding override keyword where needed

Fix infinite recursion in sealEngine()

Fix minor issue with precompiled contracts.

Difficulty needs to be 1.

Minor style improvements.

fixing osx/msvc build

fix build

Fix tests.

Avoid failing test.

Fix mining.